### ISSUE TITLE
Formule craft xp métier

### ISSUE THREAD

**Issue by Neyzv** [StarLoco/StarLoco-Game#13]
public static short GetCraftJobXp(sbyte slotsCount) =>
            slotsCount switch
            {
                3 => 50,
                4 => 75,
                5 => 125,
                6 => 250,
                7 => 500,
                8 => 750,
                _ => 25
            };

**Comment by Diabu** [comment]
Sur boune, un craft 2 case (sculpteur de baton) au niveau 31 donne bien 10 xp et non 25.
Les valeurs de l'emu correspondent aussi a ce qu'on peut trouver sur les fansites:
- https://www.dofux.org/articles-166-les-metiers.dx
- https://forums.jeuxonline.info/sujet/754473/tableaux-d-experience#titre_4
