### ISSUE TITLE
Icônes de classe à la création du perso

### ISSUE THREAD

**Issue by onderdog** [StarLoco/StarLoco-Game#153]
![icone de travers](https://github.com/StarLoco/StarLoco-Game/assets/1375521/a59c5e4f-249e-4623-af31-a234784ece08)

L'icône de classe (en dessous de notre vie) n'est pas centrée lors de la création de notre personnage.

**Comment by Diabu** [comment]
Tres probablement un bug client. Il ne me semble que l'on a 0 controle la dessus
