### ISSUE TITLE
changement de perso reste bloqué

### ISSUE THREAD

**Issue by charriamed** [StarLoco/StarLoco-Game#27]
changement de perso reste bloqué sur cette vue : 
![image](https://user-images.githubusercontent.com/90575084/229232393-e67854ac-37c8-430f-bce3-b48140815cf9.png)
pour infos: le soucis a été réglé par Arwase/Hydro , désolé faible mémoire

**Comment by Diabu** [comment]
C'est surement un soucis du cote de ta config, verifie que tu as bien:
 `system.server.exchange.key ChangeMeYn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=` defini dans la config du game ET du login.

**Comment by charriamed** [comment]
![image](https://user-images.githubusercontent.com/90575084/229310876-f9eac8c1-5cc9-40bb-96ac-b20c142c4cca.png)
