### ISSUE TITLE
Zaap Otomai ( plage + zoth non fonctionnel

### ISSUE THREAD

**Issue by charriamed** [StarLoco/StarLoco-Game#28]
zaap otomai de la plage + zoth non fonctionnel 
les 2 options : utiliser + sauvegarder sont KO

**Comment by Sukiiu** [comment]
Salut, la verif des zaap d'otomai se fait dans la classe _GameCase_ 
Elle verif une condition dans le Player : 
`    public boolean verifOtomaiZaap() {
        return Config.allZaap || !(this.getCurMap().getId() == 10643 || this.getCurMap().getId() == 11210)
                || World.world.getConditionManager().validConditions(this, "QT=231") && World.world.getConditionManager().validConditions(this, "QT=232");
    }
`

J'ai pas trop touché au quête mais j'ai l'impression que pour utiliser ce zaap,  il faut avoir la condition de validée qui semble être des quêtes (231 et 232)

**Comment by Saokkei** [comment]
En effet, il me semble qu'il faut avoir valider les quêts, on ferme l'issue ? @charriamed

**Comment by Saokkei** [comment]
En effet, il me semble qu'il faut avoir valider les quêtes, on ferme l'issue ? @charriamed

**Comment by charriamed** [comment]
yes

**Comment by StarLoco** [comment]
@Sukiiu @charriamed vous pouvez activé l'option "AllZaap" dans la config pour permettre de l'utiliser, auquel cas, oui il vous faudra la quête terminée pour pouvoir l'utiliser.
