### ISSUE TITLE
Le Tacle/Détacle sous invi ne fonctionne pas

### ISSUE THREAD

**Issue by Saokkei** [StarLoco/StarLoco-Game#49]
![](https://imgur.com/jqFodlD.gif)

On est censé tacler et dé-tacler même sous invi or là mon sram qui a moins d'agi que l'osa dé-tacle alors qu'il devrait se faire tacler.

**Comment by Diabu** [comment]
[![Dofus_Retro_65aCrhK2dH]()
](https://user-images.githubusercontent.com/183968/230921621-172e58b4-0448-4336-a18a-1c34bdc9f9ff.png)
