### ISSUE TITLE
Le message "tu ne possèdes pas l'objet nécessaire pour rentrer ici" n'apparait pas 

### ISSUE THREAD

**Issue by Saokkei** [StarLoco/StarLoco-Game#53]
Lorsqu'on ne possède pas l'objet nécessaire pour activer un trigger de changement on devrait avoir ce message qui apparaît dans le tchat : 
![](https://i.imgur.com/5Alvp5S.png)

**Comment by Diabu** [comment]
A fix via scripts en utilisant `player:sendInfoMsg`
