### ISSUE TITLE
La sacrifiée passe son tour trop vite

### ISSUE THREAD

**Issue by Fred6725** [StarLoco/StarLoco-Game#6]
Suite à nos discussions je crée un nouvel issue. :)
La sacrifiée passe ses tours très rapidement et l'animation et les dégâts ne sont parfois effectifs qu'après que le monstre qui suit dans la tabline ait eu le temps de faire des dégâts. 

-> Parfois le monstre qui suit est mort, mais il a eu le temps de jouer et de faire des dégâts avant de subir les dégâts de la sacrifiée.

**Comment by StarLoco** [comment]
Fixed with https://github.com/StarLoco/StarLoco-Game/commit/044958b16566398871679ad8329343473073b425
