### ISSUE TITLE
Impossible de connecter 8 comptes voir meme 7

### ISSUE THREAD

**Issue by MowKette** [StarLoco/StarLoco-Game#60]
Les 8 persos fonctionnent a leur creation mais impossible de reconnecter les 8 une fois le serveur arrete puis redemarre, le 8eme (ou parfois meme 7eme) compte faisant crash le serveur

**Comment by Saokkei** [comment]
Est-ce que tu peux pull le master et vérifier si le problème est toujours présent ?

**Comment by MowKette** [comment]
Ca fonctionne ! Merci !
