### ISSUE TITLE
 En combat les mobs peuvent etre affiches sur la mauvaise case

### ISSUE THREAD

**Issue by MowKette** [StarLoco/StarLoco-Game#65]
Parfois, un mob ne sera pas affiche sur la bonne case sur un ou plusieurs des comptes alors qu'il sera bien positionne sur d'autres

**Comment by StarLoco** [comment]
Des screenshots/gifs et des explications plus détaillées sur la manière de reproduire le problème sont important pour que nous puissions identifier et corriger le problème plus rapidement.

**Comment by MowKette** [comment]
[https://i.imgur.com/hjG27Im.gif](url)
Desole pour la longueur du gif

**Comment by Saokkei** [comment]
Hello MowKette, est-ce que ce bug se produit encore ?

**Comment by MowKette** [comment]
Ca semble ok maintenant
