### ISSUE TITLE
Souci de quantité d'effet sur le sort Bouture revitalisante de La Surpuissante

### ISSUE THREAD

**Issue by Fred6725** [StarLoco/StarLoco-Game#8]
Lorsque la surpuissante lance Bouture revitalisante sur La Fourbe invoquée, celle-ci devrait gagner +35 en vitalité comme indiqué par le client mais le code semble lui en attribué +70 conformément au screen qui suit :

![Starloco bug brouture](https://user-images.githubusercontent.com/127450881/224541988-3f3ad2aa-05c0-4769-90b7-4e575e2b3dd9.png)

**Comment by Saokkei** [comment]
Fixed : https://i.imgur.com/Z5qsFuH.gif
