### ISSUE TITLE
Mode épé

### ISSUE THREAD

**Issue by liberodark** [StarLoco/StarLoco-Game#85]
**Version :** c077bcfd2925dbde6384e80df1d5def72531220d

Localisation lors du test
MapID : 10319
CellID : 271

Quand le mode épé s'active :
![image](https://github.com/StarLoco/StarLoco-Game/assets/4238928/caee3ce1-d98e-4725-a2c8-4e0874ea8300)

Aucune action n'est possible : 
![image](https://github.com/StarLoco/StarLoco-Game/assets/4238928/1b7f8872-e089-47d8-938e-07df0e96f19d)

Workaround soit abandonner ou déconnecter et reconnecter.

PS : Oui je sais que c'est pas un mode mais je trouve ça drole de donner un nom à ce bug.

**Comment by Diabu** [comment]
Should be fixed now. Reopen if not
